# Generated by Django 2.2.2 on 2019-06-30 02:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 2, 49, 43, 711498, tzinfo=utc), verbose_name='date updated'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 30, 2, 49, 43, 711442, tzinfo=utc), verbose_name='date created'),
        ),
    ]
