# Generated by Django 2.2.2 on 2019-06-30 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0004_auto_20190630_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='comment_text',
            field=models.CharField(default='No comment', max_length=200),
        ),
    ]
