# Generated by Django 2.2.2 on 2019-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0005_sentence_comment_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
    ]
