# Generated by Django 2.2.2 on 2019-06-30 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sentences.Category'),
        ),
    ]
